<?php

namespace FS\AppBundle\Repository;

/**
 * StoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList(\DateTimeInterface $now, $offset, $limit)
    {
        return $this
            ->createQueryBuilder('s')
            ->select('s.id, s.text, c.name, l.code, s.begin')
            ->join('s.category', 'c')
            ->join('s.language', 'l')
            ->where('s.begin < :now')
            ->setParameter('now', $now)
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery()
            ->getArrayResult();
    }

    public function getCount(\DateTimeInterface $now)
    {
        return (int)$this
            ->createQueryBuilder('s')
            ->select('COUNT(s)')
            ->where('s.begin < :now')
            ->setParameter('now', $now)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
