<?php

namespace FS\AppBundle\Repository;

/**
 * StoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList()
    {
        return $this
            ->createQueryBuilder('s')
            ->select('s.id, s.text, c.name')
            ->join('s.category', 'c')
            ->getQuery()
            ->getArrayResult();
    }
}
