<?php

namespace FS\AppBundle\Repository;

use FS\AppBundle\Entity\User;

/**
 * UserActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserActivityRepository extends \Doctrine\ORM\EntityRepository
{
    public function create(User $user)
    {
        $table = $this->getClassMetadata()->getTableName();

        $stmt = $this->getEntityManager()->getConnection()->prepare("
            INSERT INTO `$table` (`user_id`, `activity`)
            VALUES (:userId, :activity)
            ON DUPLICATE KEY UPDATE
                `activity` =:activity;
        ");

        $stmt->execute([
            'userId' => $user->getId(),
            'activity' => date(\DateTime::ISO8601)
        ]);
    }
}
