<?php

namespace FS\AppBundle\Repository;

/**
 * UserStoryFavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStoryFavoriteRepository extends \Doctrine\ORM\EntityRepository
{
}
