<?php

namespace FS\AppBundle\Repository;

/**
 * UserStoryFavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStoryFavoriteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStoryTotalMap(array $stories)
    {
        return $this
            ->createQueryBuilder('usf')
            ->select('usf.storyId, COUNT(usf.id) AS total')
            ->where('usf.storyId IN (:stories)')
            ->setParameters([
                'stories' => $stories,
            ])
            ->addGroupBy('usf.storyId')
            ->getQuery()
            ->getArrayResult();

    }
}
