app:
    resource: "@FSAppBundle/Controller/"
    type:     annotation

api:
    resource: "@FSAppBundle/Resources/config/routing.yml"
    type: yaml

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc