services:
    fs.category.data.provider:
        class: 'FS\AppBundle\Service\CategoryDataProvider'
        arguments:
            - '@doctrine'

    fs.stoty.data.provider:
        class: 'FS\AppBundle\Service\StoryDataProvider'
        arguments:
            - '@doctrine'