services:
    fs.category.data.provider:
        class: 'FS\AppBundle\Service\CategoryDataProvider'
        arguments:
            - '@doctrine'

    fs.stoty.data.provider:
        class: 'FS\AppBundle\Service\StoryDataProvider'
        arguments:
            - '@doctrine'

    fs.auth.listener:
        class: 'FS\AppBundle\Service\AuthListener'
        arguments:
            - '@security.token_storage'
            - '@doctrine'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }