FS\AppBundle\Entity\Language:
    type: entity
    table: fs_language
    repositoryClass: FS\AppBundle\Repository\LanguageRepository

    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY

    fields:
        code:
            type: text
            nullable: false
            length: 2
            fixed: true
        name:
            type: text
            nullable: false
            length: 255
            fixed: false
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false