FS\AppBundle\Entity\Story:
    type: entity
    table: fs_story
    repositoryClass: FS\AppBundle\Repository\StoryRepository

    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY

    manyToOne:
        category:
            targetEntity: FS\AppBundle\Entity\Category
            fetch: EXTRA_LAZY
            joinColumn:
                name: category_id
                referencedColumnName: id

        language:
            targetEntity: FS\AppBundle\Entity\Language
            fetch: EXTRA_LAZY
            joinColumn:
                name: language_id
                referencedColumnName: id

    fields:
        text:
            type: text
            nullable: false
            fixed: false
        status:
            type: integer
            nullable: false
            unsigned: true
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false