FS\AppBundle\Entity\UserStoryFavorite:
    type: entity
    table: fs_user_story_favorite

    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY

    manyToOne:
        user:
            targetEntity: FS\AppBundle\Entity\User
            fetch: EXTRA_LAZY
            joinColumn:
                name: user_id
                referencedColumnName: id

        story:
            targetEntity: FS\AppBundle\Entity\Story
            fetch: EXTRA_LAZY
            joinColumn:
                name: story_id
                referencedColumnName: id

    fields:
        created:
            type: datetime
            nullable: false